import { randomUUID } from 'node:crypto';
import { Identifier } from './identifier';

export class UniqueEntityID extends Identifier<string | number> {
  static #isAutoGenerated: boolean = false
  public isAutoGenerated: boolean = false

  constructor(id?: string | number) {
    super(id)
    this.isAutoGenerated = UniqueEntityID.#isAutoGenerated
  }

  static createRandomUUID(): UniqueEntityID {
    this.#isAutoGenerated = true
    return new UniqueEntityID(randomUUID())
  }
}
